# Generated by Django 3.0.3 on 2020-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('BodyMeta', models.CharField(max_length=500)),
                ('Body', models.TextField()),
                ('DateCreated', models.DateField(auto_now=True)),
            ],
        ),
    ]
