# Generated by Django 3.0.5 on 2020-04-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Author'),
        ),
    ]
