# Generated by Django 3.0.5 on 2020-04-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('blogs', '0002_auto_20200411_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Author'),
        ),
    ]
