# Generated by Django 3.0.5 on 2020-05-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('blogs', '0002_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-DateCreated']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='Author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.Author'),
        ),
    ]
