const ACTION_TYPES = {
    FETCH_BLOGS: 'FETCH_BLOGS',
    FETCH_BLOG: 'FETCH_BLOG',
    CREATE_BLOG: 'CREATE_BLOG',
    FETCH_USER: 'FETCH_USER',
    SIGNUP: 'SIGNUP',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    SET_ALERT: 'SET_ALERT',
    CLEAR_ALERT: 'CLEAR_ALERT'
}

export default ACTION_TYPES