const ACTION_TYPES = {
    FETCH_BLOGS: "FETCH_BLOGS",
    FETCH_BLOG: "FETCH_BLOG",
    CREATE_BLOG: "CREATE_BLOG",
    EDIT_BLOG: "EDIT_BLOG",
    DELETE_BLOG: "DELETE_BLOG",
    SET_USER: "SET_USER",
    SIGNUP: "SIGNUP",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    REGISTER: "REGISTER",
    SET_ERROR: "SET_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    LOADING_UI: "LOADING_UI",
    STOP_LOADING_UI: "STOP_LOADING_UI",
    LOADING_USER: "LOADING_USER",
};

export default ACTION_TYPES;
