const ACTION_TYPES = {
    FETCH_BLOGS: "FETCH_BLOGS",
    LIKE_BLOG: "LIKE_BLOG",
    UNLIKE_BLOG: "UNLIKE_BLOG",
    FETCH_BLOG: "FETCH_BLOG",
    CREATE_BLOG: "CREATE_BLOG",
    EDIT_BLOG: "EDIT_BLOG",
    DELETE_BLOG: "DELETE_BLOG",
    SET_USER: "SET_USER",
    SET_TEMP_USER: "SET_TEMP_USER",
    SUBMIT_COMMENT: "SUBMIT_COMMENT",
    LOGOUT: "LOGOUT",
    SET_ERROR: "SET_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    LOADING_UI: "LOADING_UI",
    STOP_LOADING_UI: "STOP_LOADING_UI",
    LOADING_USER: "LOADING_USER",
    LOADING_DATA: "LOADING_DATA",
};

export default ACTION_TYPES;
