# Generated by Django 3.0.2 on 2020-01-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('AG', 'Agent'), ('AD', 'Admin')], max_length=2),
        ),
    ]
