# Generated by Django 3.0.2 on 2020-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200129_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Groups',
            new_name='GroupID',
        ),
        migrations.AddField(
            model_name='student',
            name='SubscriptionID',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
